(function(){
  const list=document.getElementById('candidateList');
  const hiringPage=document.getElementById('hiring-page');
  if(!list||!hiringPage)return;

  function escapeHtml(value=''){return String(value).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]))}
  function statusLabel(value){return ({invited:'Onboarding invited',submitted:'Submitted for review',reviewed:'Reviewed',archived:'Archived'})[value]||value||'Unknown'}
  function applicationStatus(value){return ({submitted:'New application',reviewing:'Reviewing',accepted:'Accepted',rejected:'Rejected',archived:'Archived'})[value]||value||'Unknown'}

  function setupHiringLayout(){
    const head=hiringPage.querySelector('.action-head');
    if(head&&!document.getElementById('addHiringCandidate')){
      const oldLink=head.querySelector('a[href^="onboarding.html"]');if(oldLink)oldLink.remove();
      const actions=document.createElement('div');actions.style.cssText='display:flex;gap:10px;flex-wrap:wrap;justify-content:flex-end';
      actions.innerHTML='<a class="secondary button-link" href="application.html" target="_blank" rel="noopener">Open Application Form</a><button id="copyApplicationLink" class="secondary" type="button">Copy Application Link</button><button id="addHiringCandidate" class="primary" type="button">Invite Candidate</button>';
      head.appendChild(actions);
    }
    if(!document.getElementById('applicationQueue')){
      const section=document.createElement('section');section.className='panel';section.style.marginBottom='20px';
      section.innerHTML='<div class="panel-head"><div><div class="eyebrow">APPLICATIONS</div><h2>Applicant Review Queue</h2><p style="color:var(--muted);margin:6px 0 0">Applications submitted through the Aria AI employment form appear here for review.</p></div><span id="applicationCount" class="pill pending">0 new</span></div><div id="applicationQueue" class="candidate-list" style="margin-top:16px"></div>';
      list.parentNode.insertBefore(section,list);
      const candidateHeading=document.createElement('div');candidateHeading.style.margin='26px 0 12px';candidateHeading.innerHTML='<div class="eyebrow">ONBOARDING</div><h2 style="margin:5px 0 0">Candidates & Onboarding</h2>';
      list.parentNode.insertBefore(candidateHeading,list);
    }
  }

  function addModal(){
    if(document.getElementById('hiringCandidateModal'))return;
    const backdrop=document.createElement('div');backdrop.className='modal-backdrop hidden';backdrop.id='hiringCandidateModal';backdrop.innerHTML=`<div class="modal"><button class="close" type="button" data-hiring-close aria-label="Close">×</button><div class="eyebrow">HIRING</div><h2>Invite Candidate</h2><p style="color:var(--muted);font-size:13px;line-height:1.55">Create a hiring record and a private onboarding link for the candidate.</p><label>Candidate name<input id="hiringCandidateName" maxlength="120" /></label><label>Candidate email<input id="hiringCandidateEmail" type="email" maxlength="254" /></label><label>Department<select id="hiringCandidateDepartment"><option>Operations</option><option>HR</option><option>IT</option><option>Engineering</option></select></label><label>Expected role<input id="hiringCandidateRole" maxlength="120" /></label><div id="hiringInviteResult" class="notice hidden" style="margin-top:16px"></div><div class="modal-actions"><button class="primary" id="saveHiringCandidate" type="button">Create Onboarding Link</button></div></div>`;document.body.appendChild(backdrop)
  }
  function openModal(){document.getElementById('hiringInviteResult')?.classList.add('hidden');['hiringCandidateName','hiringCandidateEmail','hiringCandidateRole'].forEach(id=>{const el=document.getElementById(id);if(el)el.value=''});document.getElementById('hiringCandidateModal')?.classList.remove('hidden')}
  function closeModal(){document.getElementById('hiringCandidateModal')?.classList.add('hidden')}

  async function loadApplications(){
    const queue=document.getElementById('applicationQueue');if(!queue)return;queue.innerHTML='<div class="empty-queue">Loading applications…</div>';
    try{
      const response=await fetch('/api/staff/hiring/applications',{credentials:'same-origin',cache:'no-store'});const data=await response.json().catch(()=>({}));if(!response.ok||!data.ok)throw new Error(data.error||'Unable to load applications.');const apps=data.applications||[];
      const count=document.getElementById('applicationCount');if(count)count.textContent=`${apps.filter(a=>a.status==='submitted').length} new`;
      queue.innerHTML=apps.length?apps.map(app=>{const location=[app.city,app.state].filter(Boolean).join(', ');const details=[app.email,app.phone,location].filter(Boolean).join(' • ');let actions='';if(app.status==='submitted')actions=`<button class="secondary app-action" data-action="reviewing" data-id="${escapeHtml(app.id)}">Start Review</button><button class="primary app-action" data-action="accept" data-id="${escapeHtml(app.id)}">Accept</button><button class="secondary app-action" data-action="reject" data-id="${escapeHtml(app.id)}">Reject</button>`;else if(app.status==='reviewing')actions=`<button class="primary app-action" data-action="accept" data-id="${escapeHtml(app.id)}">Accept</button><button class="secondary app-action" data-action="reject" data-id="${escapeHtml(app.id)}">Reject</button>`;else actions=`<button class="secondary app-action" data-action="archive" data-id="${escapeHtml(app.id)}">Archive</button>`;return `<article class="candidate-card"><div class="candidate-meta"><strong>${escapeHtml(app.full_name)}</strong><span>${escapeHtml(app.department)} • ${escapeHtml(app.desired_role)} • ${escapeHtml(app.employment_type)}</span><span>${escapeHtml(details)}</span>${app.availability?`<span>Availability: ${escapeHtml(app.availability)}</span>`:''}${app.experience_summary?`<div style="margin-top:10px;font-size:12px;color:var(--muted);line-height:1.55"><strong style="color:var(--text)">Experience</strong><br>${escapeHtml(app.experience_summary)}</div>`:''}${app.why_aria?`<div style="margin-top:8px;font-size:12px;color:var(--muted);line-height:1.55"><strong style="color:var(--text)">Why Aria AI</strong><br>${escapeHtml(app.why_aria)}</div>`:''}</div><div class="candidate-actions"><span class="pill ${app.status==='accepted'?'active':app.status==='rejected'?'high':app.status==='reviewing'?'in-progress':'pending'}">${escapeHtml(applicationStatus(app.status))}</span>${actions}</div></article>`}).join(''):'<div class="empty-queue">No applications yet. Share the application link when you are ready to hire.</div>';
    }catch(error){queue.innerHTML=`<div class="empty-queue">${escapeHtml(error?.message||'Unable to load applications.')}</div>`}
  }

  async function applicationAction(id,action){
    try{const response=await fetch(`/api/staff/hiring/applications/${encodeURIComponent(id)}`,{method:'POST',headers:{'content-type':'application/json'},credentials:'same-origin',body:JSON.stringify({action})});const data=await response.json().catch(()=>({}));if(!response.ok||!data.ok)throw new Error(data.error||'Unable to update application.');if(action==='accept'&&data.onboardingUrl){try{await navigator.clipboard.writeText(data.onboardingUrl);alert('Applicant accepted. The onboarding link was copied to your clipboard.')}catch{prompt('Applicant accepted. Copy this onboarding link:',data.onboardingUrl)}}await Promise.all([loadApplications(),loadCandidates()])}catch(error){alert(error?.message||'Unable to update application.')}
  }

  async function loadCandidates(){
    list.innerHTML='<div class="empty-queue">Loading hiring records…</div>';
    try{const response=await fetch('/api/staff/hiring/candidates',{credentials:'same-origin',cache:'no-store'});const data=await response.json().catch(()=>({}));if(!response.ok||!data.ok)throw new Error(data.error||'Unable to load hiring records.');const records=data.candidates||[];list.innerHTML=records.length?records.map(candidate=>{const submitted=candidate.status==='submitted'||candidate.status==='reviewed';const detail=submitted?`<div style="margin-top:12px;padding-top:12px;border-top:1px solid var(--line);font-size:12px;color:var(--muted);line-height:1.6"><strong style="color:var(--text)">Onboarding submission</strong><br>${escapeHtml(candidate.personal_email||candidate.email)} • ${escapeHtml(candidate.phone||'No phone')}<br>${escapeHtml([candidate.city,candidate.state].filter(Boolean).join(', '))} • Start ${escapeHtml(candidate.preferred_start_date||'Not provided')} • ${escapeHtml(candidate.availability||'')}${candidate.notes?`<div style="margin-top:7px">${escapeHtml(candidate.notes)}</div>`:''}</div>`:'';const action=candidate.status==='submitted'?`<button class="secondary hiring-reviewed" data-id="${escapeHtml(candidate.id)}" type="button">Mark Reviewed</button>`:'';return `<article class="candidate-card"><div class="candidate-meta"><strong>${escapeHtml(candidate.full_name)}</strong><span>${escapeHtml(candidate.email)} • ${escapeHtml(candidate.department||'Department pending')} • ${escapeHtml(candidate.expected_role||'Role pending')}</span>${detail}</div><div class="candidate-actions"><span class="pill ${candidate.status==='reviewed'?'active':candidate.status==='submitted'?'in-progress':'pending'}">${escapeHtml(statusLabel(candidate.status))}</span>${action}</div></article>`}).join(''):'<div class="empty-queue">No onboarding candidates yet.</div>';const pending=document.getElementById('pendingCount');if(pending)pending.textContent=String(records.filter(c=>c.status!=='reviewed'&&c.status!=='archived').length)}catch(error){list.innerHTML=`<div class="empty-queue">${escapeHtml(error?.message||'Unable to load hiring records.')}</div>`}
  }

  async function createCandidate(){const button=document.getElementById('saveHiringCandidate'),fullName=document.getElementById('hiringCandidateName').value.trim(),email=document.getElementById('hiringCandidateEmail').value.trim(),department=document.getElementById('hiringCandidateDepartment').value,expectedRole=document.getElementById('hiringCandidateRole').value.trim();if(!fullName||!email||!expectedRole){alert('Candidate name, email, and expected role are required.');return}button.disabled=true;button.textContent='Creating…';try{const response=await fetch('/api/staff/hiring/candidates',{method:'POST',headers:{'content-type':'application/json'},credentials:'same-origin',body:JSON.stringify({fullName,email,department,expectedRole})});const data=await response.json().catch(()=>({}));if(!response.ok||!data.ok)throw new Error(data.error||'Unable to create candidate invitation.');const result=document.getElementById('hiringInviteResult');result.innerHTML=`<strong>Onboarding link created.</strong><div style="margin-top:8px;word-break:break-all">${escapeHtml(data.onboardingUrl||'')}</div><button class="secondary" id="copyHiringLink" type="button" style="margin-top:10px">Copy Link</button><div style="margin-top:8px;font-size:11px">The link expires in 7 days.</div>`;result.classList.remove('hidden');document.getElementById('copyHiringLink')?.addEventListener('click',async event=>{try{await navigator.clipboard.writeText(data.onboardingUrl||'');event.currentTarget.textContent='Copied'}catch{}});await loadCandidates()}catch(error){alert(error?.message||'Unable to create candidate invitation.')}finally{button.disabled=false;button.textContent='Create Onboarding Link'}}
  async function markReviewed(id){try{const response=await fetch(`/api/staff/hiring/candidates/${encodeURIComponent(id)}/reviewed`,{method:'POST',credentials:'same-origin'});const data=await response.json().catch(()=>({}));if(!response.ok||!data.ok)throw new Error(data.error||'Unable to mark onboarding reviewed.');await loadCandidates()}catch(error){alert(error?.message||'Unable to mark onboarding reviewed.')}}

  setupHiringLayout();addModal();
  document.getElementById('addHiringCandidate')?.addEventListener('click',openModal);document.querySelector('[data-hiring-close]')?.addEventListener('click',closeModal);document.getElementById('hiringCandidateModal')?.addEventListener('click',event=>{if(event.target.id==='hiringCandidateModal')closeModal()});document.getElementById('saveHiringCandidate')?.addEventListener('click',createCandidate);document.getElementById('copyApplicationLink')?.addEventListener('click',async event=>{const url=`${location.origin}/application.html`;try{await navigator.clipboard.writeText(url);event.currentTarget.textContent='Application Link Copied';setTimeout(()=>event.currentTarget.textContent='Copy Application Link',1500)}catch{prompt('Copy application link:',url)}});document.addEventListener('click',event=>{const review=event.target.closest('.hiring-reviewed');if(review)markReviewed(review.dataset.id);const app=event.target.closest('.app-action');if(app)applicationAction(app.dataset.id,app.dataset.action)});
  Promise.all([loadApplications(),loadCandidates()]);
})();
