function json(data,init={}){return new Response(JSON.stringify(data),{...init,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff',...(init.headers||{})}})}
function uuid(prefix){return `${prefix}-${crypto.randomUUID()}`}
function bytesToHex(bytes){return [...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function sha256(value){return bytesToHex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(value))))}
function parseCookies(request){const raw=request.headers.get('cookie')||'';return Object.fromEntries(raw.split(';').map(v=>v.trim()).filter(Boolean).map(v=>{const i=v.indexOf('=');return[v.slice(0,i),decodeURIComponent(v.slice(i+1))]}))}
async function readBody(request){try{return await request.json()}catch{return null}}
function clean(value,max=1000){return String(value||'').trim().slice(0,max)}

async function currentSession(request,env){const token=parseCookies(request).aria_session;if(!token||!env.DB)return null;const tokenHash=await sha256(token);return env.DB.prepare(`SELECT s.id AS session_id,u.id AS user_id,u.email,u.display_name,u.account_type,u.status,(SELECT role_name FROM staff_roles r WHERE r.user_id=u.id AND r.active=1 ORDER BY r.assigned_at DESC LIMIT 1) AS staff_role,(SELECT department FROM staff_roles r WHERE r.user_id=u.id AND r.active=1 ORDER BY r.assigned_at DESC LIMIT 1) AS department FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.revoked_at IS NULL AND s.expires_at>? LIMIT 1`).bind(tokenHash,new Date().toISOString()).first()}
async function requireHrAccess(request,env){const session=await currentSession(request,env);if(!session||session.account_type!=='staff'||session.status!=='active')return{error:json({ok:false,error:'Authentication required.'},{status:401})};const role=String(session.staff_role||'').trim().toLowerCase(),department=String(session.department||'').trim().toLowerCase();const allowed=['founder','founder / co-founder','co-founder','hr','human resources'].includes(role)||department==='hr'||department==='human resources';if(!allowed)return{error:json({ok:false,error:'You do not have permission to access HR cases.'},{status:403})};return{session,role,department}}
async function recordAudit(env,event){const now=new Date().toISOString();await env.DB.prepare(`INSERT INTO audit_events (id,category,event_type,actor_user_id,subject_type,subject_id,details_json,occurred_at,recorded_at) VALUES (?,'Human Resources',?,?,?,?,?,?,?)`).bind(uuid('AUD'),event.eventType,event.actorUserId||null,event.subjectType||'hr_case',event.subjectId||null,JSON.stringify(event.details||{}),now,now).run()}

async function listEmployees(request,env){const auth=await requireHrAccess(request,env);if(auth.error)return auth.error;const result=await env.DB.prepare(`SELECT u.id,u.display_name,u.email,u.status,(SELECT role_name FROM staff_roles r WHERE r.user_id=u.id AND r.active=1 ORDER BY r.assigned_at DESC LIMIT 1) AS role_name,(SELECT department FROM staff_roles r WHERE r.user_id=u.id AND r.active=1 ORDER BY r.assigned_at DESC LIMIT 1) AS department FROM users u WHERE u.account_type='staff' AND u.status IN ('active','suspended') ORDER BY u.display_name COLLATE NOCASE ASC`).all();return json({ok:true,employees:result.results||[]})}

async function listCases(request,env){const auth=await requireHrAccess(request,env);if(auth.error)return auth.error;const cases=await env.DB.prepare(`SELECT c.id,c.employee_user_id,c.case_type,c.priority,c.title,c.details,c.status,c.progress,c.created_at,c.updated_at,c.closed_at,e.display_name AS employee_name,e.email AS employee_email,(SELECT department FROM staff_roles r WHERE r.user_id=e.id AND r.active=1 ORDER BY r.assigned_at DESC LIMIT 1) AS employee_department,o.display_name AS opened_by_name FROM hr_cases c JOIN users e ON e.id=c.employee_user_id LEFT JOIN users o ON o.id=c.opened_by_user_id ORDER BY CASE c.status WHEN 'Open' THEN 0 WHEN 'In Progress' THEN 1 ELSE 2 END,c.updated_at DESC LIMIT 200`).all();const rows=cases.results||[];if(!rows.length)return json({ok:true,cases:[]});const notes=await env.DB.prepare(`SELECT n.id,n.case_id,n.note,n.created_at,u.display_name AS author_name FROM hr_case_notes n JOIN users u ON u.id=n.author_user_id ORDER BY n.created_at ASC`).all();const byCase=new Map();for(const note of notes.results||[]){if(!byCase.has(note.case_id))byCase.set(note.case_id,[]);byCase.get(note.case_id).push(note)}return json({ok:true,cases:rows.map(row=>({...row,notes:byCase.get(row.id)||[]}))})}

async function createCase(request,env){const auth=await requireHrAccess(request,env);if(auth.error)return auth.error;const body=await readBody(request);const employeeUserId=clean(body?.employeeUserId,180),caseType=clean(body?.caseType,100),priority=clean(body?.priority,20),title=clean(body?.title,120),details=clean(body?.details,2000);if(!employeeUserId||!caseType||!title||!details)return json({ok:false,error:'Employee, case type, title, and details are required.'},{status:400});if(!['Normal','High','Urgent'].includes(priority))return json({ok:false,error:'Select a valid priority.'},{status:400});const employee=await env.DB.prepare(`SELECT id,display_name,status FROM users WHERE id=? AND account_type='staff' LIMIT 1`).bind(employeeUserId).first();if(!employee)return json({ok:false,error:'Employee account not found.'},{status:404});const id=uuid('HR'),now=new Date().toISOString();await env.DB.prepare(`INSERT INTO hr_cases (id,employee_user_id,case_type,priority,title,details,status,progress,opened_by_user_id,created_at,updated_at) VALUES (?,?,?,?,?,?,'Open',0,?,?,?)`).bind(id,employeeUserId,caseType,priority,title,details,auth.session.user_id,now,now).run();await recordAudit(env,{eventType:'hr_case_created',actorUserId:auth.session.user_id,subjectId:id,details:{employeeUserId,employeeName:employee.display_name,caseType,priority,title}});return json({ok:true,id,status:'Open',progress:0},{status:201})}

async function updateCase(request,env,id){const auth=await requireHrAccess(request,env);if(auth.error)return auth.error;const row=await env.DB.prepare(`SELECT id,status,progress,employee_user_id FROM hr_cases WHERE id=? LIMIT 1`).bind(id).first();if(!row)return json({ok:false,error:'HR case not found.'},{status:404});const body=await readBody(request),status=body?.status===undefined?row.status:clean(body.status,40),progress=body?.progress===undefined?Number(row.progress):Number(body.progress);if(!['Open','In Progress','Closed'].includes(status))return json({ok:false,error:'Invalid case status.'},{status:400});if(![0,25,50,75,100].includes(progress))return json({ok:false,error:'Progress must be 0, 25, 50, 75, or 100.'},{status:400});let finalStatus=status,finalProgress=progress;if(finalProgress===100)finalStatus='Closed';else if(finalProgress>0&&finalStatus==='Open')finalStatus='In Progress';else if(finalProgress===0&&finalStatus==='Closed')finalStatus='Open';if(finalStatus==='Closed')finalProgress=100;const now=new Date().toISOString(),closedAt=finalStatus==='Closed'?now:null;await env.DB.prepare(`UPDATE hr_cases SET status=?,progress=?,updated_at=?,closed_at=? WHERE id=?`).bind(finalStatus,finalProgress,now,closedAt,id).run();await recordAudit(env,{eventType:'hr_case_updated',actorUserId:auth.session.user_id,subjectId:id,details:{status:finalStatus,progress:finalProgress,employeeUserId:row.employee_user_id}});return json({ok:true,status:finalStatus,progress:finalProgress,updatedAt:now})}

async function addNote(request,env,id){const auth=await requireHrAccess(request,env);if(auth.error)return auth.error;const row=await env.DB.prepare(`SELECT id FROM hr_cases WHERE id=? LIMIT 1`).bind(id).first();if(!row)return json({ok:false,error:'HR case not found.'},{status:404});const body=await readBody(request),note=clean(body?.note,1200);if(!note)return json({ok:false,error:'Enter a note before saving.'},{status:400});const noteId=uuid('HRN'),now=new Date().toISOString();await env.DB.batch([env.DB.prepare(`INSERT INTO hr_case_notes (id,case_id,author_user_id,note,created_at) VALUES (?,?,?,?,?)`).bind(noteId,id,auth.session.user_id,note,now),env.DB.prepare(`UPDATE hr_cases SET updated_at=? WHERE id=?`).bind(now,id)]);await recordAudit(env,{eventType:'hr_case_note_added',actorUserId:auth.session.user_id,subjectId:id,details:{noteId}});return json({ok:true,note:{id:noteId,note,created_at:now,author_name:auth.session.display_name||'HR staff'}},{status:201})}

export async function handleHrRoute(request,env){const url=new URL(request.url);if(url.pathname==='/api/staff/hr/employees'&&request.method==='GET')return listEmployees(request,env);if(url.pathname==='/api/staff/hr/cases'&&request.method==='GET')return listCases(request,env);if(url.pathname==='/api/staff/hr/cases'&&request.method==='POST')return createCase(request,env);const caseMatch=url.pathname.match(/^\/api\/staff\/hr\/cases\/([^/]+)$/);if(caseMatch&&request.method==='PATCH')return updateCase(request,env,decodeURIComponent(caseMatch[1]));const noteMatch=url.pathname.match(/^\/api\/staff\/hr\/cases\/([^/]+)\/notes$/);if(noteMatch&&request.method==='POST')return addNote(request,env,decodeURIComponent(noteMatch[1]));return null}
