(function(){
  const page=document.getElementById('hr-page'),queue=document.getElementById('hrQueue'),summary=document.getElementById('hrSummary');
  if(!page||!queue||!summary)return;
  let employees=[],cases=[];
  function esc(v=''){return String(v).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]))}
  function fmt(v){if(!v)return'';try{return new Intl.DateTimeFormat('en-US',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))}catch{return v}}
  function statusClass(v=''){return String(v).toLowerCase().replaceAll(' ','-')}

  function addModal(){if(document.getElementById('liveHrModal'))return;const modal=document.createElement('div');modal.id='liveHrModal';modal.className='modal-backdrop hidden';modal.innerHTML=`<div class="modal"><button class="close" type="button" data-live-hr-close aria-label="Close">×</button><div class="eyebrow">HUMAN RESOURCES</div><h2>Create HR Case</h2><p style="color:var(--muted);font-size:13px;line-height:1.55">Create a controlled employee case. Access is limited to authorized HR staff and Founder.</p><label>Employee<select id="liveHrEmployee"></select></label><label>Case type<select id="liveHrType"><option>Coaching / Counseling</option><option>Attendance</option><option>Conduct</option><option>Performance</option><option>Written Warning</option><option>Final Warning</option><option>Policy Review</option><option>Other</option></select></label><label>Priority<select id="liveHrPriority"><option>Normal</option><option>High</option><option>Urgent</option></select></label><label>Case title<input id="liveHrTitle" maxlength="120" placeholder="Short internal title" /></label><label>Details<textarea id="liveHrDetails" maxlength="2000" placeholder="Document the facts and required follow-up"></textarea></label><div class="modal-actions"><button class="primary" id="liveHrSave" type="button">Create Case</button><button class="secondary" data-live-hr-close type="button">Cancel</button></div></div>`;document.body.appendChild(modal);document.querySelectorAll('[data-live-hr-close]').forEach(b=>b.addEventListener('click',()=>modal.classList.add('hidden')));modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.add('hidden')});document.getElementById('liveHrSave')?.addEventListener('click',createCase)}
  function openModal(){const select=document.getElementById('liveHrEmployee');select.innerHTML=employees.length?employees.map(e=>`<option value="${esc(e.id)}">${esc(e.display_name||e.email)} — ${esc(e.department||'No department')}</option>`).join(''):'<option value="">No staff accounts available</option>';document.getElementById('liveHrType').value='Coaching / Counseling';document.getElementById('liveHrPriority').value='Normal';document.getElementById('liveHrTitle').value='';document.getElementById('liveHrDetails').value='';document.getElementById('liveHrModal').classList.remove('hidden')}

  async function loadEmployees(){const r=await fetch('/api/staff/hr/employees',{credentials:'same-origin',cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||'Unable to load employees.');employees=d.employees||[]}
  async function loadCases(){queue.innerHTML='<div class="empty-queue">Loading HR cases…</div>';const r=await fetch('/api/staff/hr/cases',{credentials:'same-origin',cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||'Unable to load HR cases.');cases=d.cases||[];render()}
  async function loadAll(){try{await Promise.all([loadEmployees(),loadCases()]);sessionStorage.removeItem('aria-staff-hr-cases')}catch(e){queue.innerHTML=`<div class="empty-queue">${esc(e?.message||'Unable to load HR workspace.')}</div>`}}

  function progressBlock(c){const p=Number(c.progress)||0;return `<div style="margin-top:14px;max-width:520px"><div style="display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:6px"><span style="font-size:11px;font-weight:800;color:#657185">Progress</span><strong style="font-size:12px;color:#4d5a70">${p}%</strong></div><div style="height:8px;background:#eef1f5;border-radius:999px;overflow:hidden"><span style="display:block;height:100%;width:${p}%;background:linear-gradient(90deg,#6269e5,#895fd8);border-radius:999px"></span></div><div style="display:flex;gap:6px;flex-wrap:wrap;margin-top:8px">${[0,25,50,75,100].map(v=>`<button class="status-btn live-hr-progress" data-id="${esc(c.id)}" data-progress="${v}" ${p===v?'disabled style="opacity:.55;cursor:default"':''}>${v}%</button>`).join('')}</div></div>`}
  function notesBlock(c){const notes=c.notes||[];return `<div style="margin-top:16px;padding-top:14px;border-top:1px solid var(--line)"><div style="font-size:11px;font-weight:800;color:#657185;margin-bottom:8px">PRIVATE HR NOTES</div>${notes.length?`<div style="display:grid;gap:8px;margin-bottom:10px">${notes.map(n=>`<div style="padding:10px 12px;border:1px solid var(--line);border-radius:12px;background:#fafbfc"><div style="font-size:11px;color:#7d8899;margin-bottom:4px">${esc(n.author_name||'HR staff')} • ${esc(fmt(n.created_at))}</div><div style="font-size:12px;line-height:1.5">${esc(n.note)}</div></div>`).join('')}</div>`:'<div style="font-size:12px;color:var(--muted);margin-bottom:10px">No private notes yet.</div>'}<div style="display:flex;gap:8px;align-items:flex-end;flex-wrap:wrap"><textarea class="live-hr-note-input" data-id="${esc(c.id)}" maxlength="1200" placeholder="Add a private HR note" style="flex:1;min-width:220px;min-height:74px;border:1px solid #dfe5ed;border-radius:11px;padding:10px 12px;resize:vertical"></textarea><button class="secondary live-hr-note-save" data-id="${esc(c.id)}" type="button">Save Note</button></div></div>`}
  function render(){const open=cases.filter(c=>c.status==='Open').length,progress=cases.filter(c=>c.status==='In Progress').length,closed=cases.filter(c=>c.status==='Closed').length;summary.innerHTML=`<span class="summary-chip">Open <strong>${open}</strong></span><span class="summary-chip">In Progress <strong>${progress}</strong></span><span class="summary-chip">Closed <strong>${closed}</strong></span><span class="summary-chip">Total <strong>${cases.length}</strong></span>`;const dashboard=document.getElementById('openHrCount');if(dashboard)dashboard.textContent=String(open+progress);queue.innerHTML=cases.length?cases.map(c=>`<article class="ticket-card"><div class="ticket-main"><div class="ticket-id">${esc(c.id)} • ${esc(c.case_type)} • ${esc(fmt(c.created_at))}</div><h3>${esc(c.title)}</h3><p>${esc(c.details)}</p><div style="margin-top:8px;font-size:12px;color:var(--muted)"><strong style="color:var(--text)">${esc(c.employee_name||'Employee')}</strong> • ${esc(c.employee_email||'')} ${c.employee_department?`• ${esc(c.employee_department)}`:''}</div><div class="ticket-meta"><span class="pill ${esc(String(c.priority).toLowerCase())}">${esc(c.priority)}</span><span class="pill ${esc(statusClass(c.status))}">${esc(c.status)}</span><span class="pill">Opened by ${esc(c.opened_by_name||'HR')}</span></div>${progressBlock(c)}${notesBlock(c)}</div><div class="ticket-actions">${c.status==='Open'?`<button class="status-btn live-hr-status" data-id="${esc(c.id)}" data-status="In Progress">Start</button>`:''}${c.status!=='Closed'?`<button class="status-btn live-hr-status" data-id="${esc(c.id)}" data-status="Closed">Close</button>`:`<button class="status-btn live-hr-status" data-id="${esc(c.id)}" data-status="Open">Reopen</button>`}</div></article>`).join(''):'<div class="empty-queue">No HR cases. Create one when employee follow-up needs to be documented.</div>'}

  async function createCase(){const button=document.getElementById('liveHrSave'),employeeUserId=document.getElementById('liveHrEmployee').value,caseType=document.getElementById('liveHrType').value,priority=document.getElementById('liveHrPriority').value,title=document.getElementById('liveHrTitle').value.trim(),details=document.getElementById('liveHrDetails').value.trim();if(!employeeUserId||!title||!details){alert('Employee, title, and details are required.');return}button.disabled=true;button.textContent='Creating…';try{const r=await fetch('/api/staff/hr/cases',{method:'POST',headers:{'content-type':'application/json'},credentials:'same-origin',body:JSON.stringify({employeeUserId,caseType,priority,title,details})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||'Unable to create HR case.');document.getElementById('liveHrModal').classList.add('hidden');await loadCases()}catch(e){alert(e?.message||'Unable to create HR case.')}finally{button.disabled=false;button.textContent='Create Case'}}
  async function patchCase(id,payload){const r=await fetch(`/api/staff/hr/cases/${encodeURIComponent(id)}`,{method:'PATCH',headers:{'content-type':'application/json'},credentials:'same-origin',body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||'Unable to update HR case.');await loadCases()}
  async function saveNote(id){const input=document.querySelector(`.live-hr-note-input[data-id="${CSS.escape(id)}"]`),note=input?.value.trim();if(!note)return;const r=await fetch(`/api/staff/hr/cases/${encodeURIComponent(id)}/notes`,{method:'POST',headers:{'content-type':'application/json'},credentials:'same-origin',body:JSON.stringify({note})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||'Unable to save HR note.');await loadCases()}

  addModal();
  document.addEventListener('click',event=>{const add=event.target.closest('#addHrCase');if(add){event.preventDefault();event.stopImmediatePropagation();openModal();return}const status=event.target.closest('.live-hr-status');if(status){event.preventDefault();patchCase(status.dataset.id,{status:status.dataset.status,progress:status.dataset.status==='Closed'?100:status.dataset.status==='Open'?0:25}).catch(e=>alert(e.message));return}const progress=event.target.closest('.live-hr-progress');if(progress){event.preventDefault();patchCase(progress.dataset.id,{progress:Number(progress.dataset.progress)}).catch(e=>alert(e.message));return}const note=event.target.closest('.live-hr-note-save');if(note){event.preventDefault();saveNote(note.dataset.id).catch(e=>alert(e.message));}},true);
  loadAll();
})();
